language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake

env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  # Get new version of boost 
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost


install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi


before_script:
  - mkdir build
  - cd build
  - cmake -DBoost_NO_SYSTEM_PATHS=TRUE VERBOSE=1 ..

script: make VERBOSE=1
